<?php 
$name=$_REQUEST['name']);
$email=$_REQUEST['email'];
$username=$_REQUEST['username'];
$password=$_REQUEST['password'];
$confirmPassword=$_REQUEST['confirmPassword'];
$dob=$_REQUEST['dob'];
$gender=$_REQUEST['gender'];
$status=$_REQUEST['status'];
$address=$_REQUEST['address'];
$city=$_REQUEST['city'];
$post=$_REQUEST['post'];
$hphone=$_REQUEST['hphone'];
$mphone=$_REQUEST['mphone'];
$cardNum=$_REQUEST['cardNum'];
$cardExp=$_REQUEST['cardExp'];
$salary=$_REQUEST['salary'];
$webUrl=$_REQUEST['webUrl'];
$gpa=$_REQUEST['gpa'];	

?>